#!/bin/bash
if [ "$1" = "" ]
then
        echo "USAGE:"
        echo "$0 <kernel-mod>"
        exit 99
fi

MOD=$1

STATUS=`lsmod | grep -w "^$MOD"`
if [ -z "$STATUS" ]; then
        echo "CRITICAL - Kernel module $MOD not loaded!"
        exit 2
fi

DATA=( $STATUS )

echo "OK - ${DATA[0]} has ${DATA[2]} instances, ${DATA[1]} bytes.|instances=${DATA[2]}, memory_usage=${DATA[1]}"
exit 0
